version: '3'

services:

  raw_data_db:
    image: postgres:latest
    container_name: raw_data_db
    environment:
      POSTGRES_DB: raw_data
      POSTGRES_USER: my_username
      POSTGRES_PASSWORD: my_password
    ports:
      - "5433:5432"
    volumes:
      - /path/to/store/data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-enterprise-kafka:latest
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
    depends_on:
      - zookeeper


  producer:
    build:
      context: .
      dockerfile: ./DockerfileProducer
    volumes:
      - ./producer.py:/app/producer.py
      - ./data_cleaned_1000.csv:/app/data_cleaned_1000.csv
    command: sh -c "sleep 10 && python /app/producer.py"

  consumer:
    build:
      context: .
      dockerfile: ./DockerfileConsumer
    volumes:
      - ./consumer.py:/app/consumer.py
    command: sh -c "sleep 20 && python /app/consumer.py"








